### ISSUE TITLE
Wrong flutter command path after updating

### ISSUE THREAD

**Issue by Charly6596** [iamcco/coc-flutter#96] opened 2021-03-01 02:25 UTC
**Describe the bug**
I've installed `coc-flutter` on December and didn't update it until yesterday. I didn't modify any option regarding to executables or anything. As the title says, the flutter command path detected not correct, as shown in the logs later on
**To Reproduce**
My coc-settings.json flutter related lines:
```json
  "flutter.lsp.initialization.closingLabels": true,
  "flutter.lsp.debug": true,
  "flutter.trace.server": "verbose",
```
flutter --version
```
$ flutter --version
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```
Execute any flutter command (flutter pub get on save, :CocCommands flutter.devices..)

**Expected behavior**
I expect it to work as usual it did before, not specifying the path manually 
**Screenshots**
![image](https://user-images.githubusercontent.com/13708100/109443528-15109700-7a3b-11eb-922d-da9a4a678934.png)
![image](https://user-images.githubusercontent.com/13708100/109443628-4c7f4380-7a3b-11eb-878b-edc5b5362f0c.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Vim or Neovim: Neovim
 - (Neo)vim version: v0.4.4

**Output channel:**
```
[dev-command]: register dev command
[sdk]: which flutter command => /var/lib/snapd/snap/bin/flutter
[sdk]: flutter command path => /usr/bin/snap/bin/flutter
[sdk]: dart sdk home => /usr/bin/cache/dart-sdk
[sdk]: which dart command => /usr/bin/dart
[sdk]: dart command path => /opt/dart-sdk/bin/dart
[sdk]: dart sdk home => /opt/dart-sdk
[sdk]: analyzer path => /opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
[sdk]: dart command path => /opt/dart-sdk/bin/dart
[fs]: executing command /opt/dart-sdk/bin/dart --version
[sdk]: dart version: v2.10.4
[lsp-server]: rightVersion true
[global-commands]: pub get command, workspace: /home/username/project-path
[fs]: executing command /usr/bin/snap/bin/flutter pub get
[fs]: executing command /usr/bin/snap/bin/flutter emulators
[dev-command]: run dev server, devServer state: false
[server]: server start at: /home/username/project-path
```

**Comment by Kavantix** [comment] 2021-03-01 07:28
Duplicate of #87 

We will support snap by default after landing #91, for now you can add this to your config:
`"flutter.sdk.flutter-lookup": "echo ~/snap/flutter/common/flutter"`
If that doesnt work you might have to replace the ~ with the path to your home directory

**Closed** 2021-03-02 09:20 UTC

**Comment by Charly6596** [comment] 2021-03-02 23:04
Hello, I'm still getting the same issue, it shows the same command not found error whenever I execute a flutter command. I've tried deleting coc-flutter and reinstalling just in case.
There is however a small difference in the output channel:
```
[dev-command]: register dev command
[sdk]: which flutter command => /var/lib/snapd/snap/bin/flutter
[sdk]: flutter command path => /usr/bin/snap/bin/flutter
[sdk]: dart sdk home => /usr/bin/cache/dart-sdk
[sdk]: which dart command => /usr/bin/dart
[sdk]: dart command path => /opt/dart-sdk/bin/dart
[sdk]: dart sdk home => /opt/dart-sdk
[sdk]: analyzer path => /opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
[sdk]: dart command path => /opt/dart-sdk/bin/dart
[fs]: executing command /opt/dart-sdk/bin/dart --version
[sdk]: dart version: v2.10.4
[lsp-server]: rightVersion true
[Trace - 11:53:13 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 28643,
    "rootPath": "/home/user/project-path",
    "rootUri": "file:///home/user/project-path",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
// just more json looking data
```
It works if i add `  "flutter.sdk.flutter-lookup": "echo $HOME/snap/flutter/common/flutter"` to the coc config file (`~` instead of `$HOME` also works)

**Comment by Charly6596** [comment] 2021-03-02 23:30
I've navigated to the coc-flutter package.json and it's missing the new changes. I assume it is because the version number didn't change and it's being installed from cache?

**Comment by iamcco** [comment] 2021-03-03 04:05
Just publish version v1.8.0, should be works now.
